os: linux
dist: bionic

language: python
python:
  - '3.8'
cache: pip

services:
  - docker

# build only the master branch or tags like #.#.#
branches:
  only:
    - master
    - /^[0-9]+(\.[0-9]+){2}$/

install: true

jobs:
  fast_finish: true
  include:

    - name: Test
      stage: test
      before_script:
        - docker-compose -f docker-compose-test.yml up -d elasticsearch kibana redis
        - docker-compose -f docker-compose-test.yml build consumer-test
      script:
        - docker-compose -f docker-compose-test.yml run --rm consumer-test test_unit
        - docker-compose -f docker-compose-test.yml run --rm consumer-test test_integration
      after_failure: docker-compose -f docker-compose-test.yml logs
      after_script: docker-compose -f docker-compose-test.yml down -v

    - name: Release
      stage: deploy
      before_script: docker login -u ehealthafricadevops -p $DOCKER_HUB_PASSWORD
      script: ./scripts/release.sh
      # release only if tag like #.#.# (never in forks or pull requests)
      if: |
        fork IS false AND \
        type != pull_request AND \
        tag =~ ^[0-9]+(\.[0-9]+){2}$
