os: linux
dist: bionic

language: python
python:
  - '3.8'
cache: pip

services:
  - docker

# build only the master branch or tags like #.#.#
branches:
  only:
    - master
    - /^[0-9]+(\.[0-9]+){2}$/

jobs:
  fast_finish: true
  include:

    - name: "Test"
      stage: test
      install: true
      script: "./scripts/run_travis.sh"

    - name: "Release"
      stage: deploy
      install: true
      before_script: docker login -u ehealthafricadevops -p $DOCKER_HUB_PASSWORD
      script: "./scripts/release.sh"
      # release only if tag like #.#.# (never in forks or pull requests)
      if: |
        fork IS false AND \
        type != pull_request AND \
        tag =~ ^[0-9]+(\.[0-9]+){2}$
