os: linux
dist: bionic

language: shell

services:
  - docker

# build only the master branch or tags like #.#.#
branches:
  only:
    - master
    - /^[0-9]+(\.[0-9]+){2}$/

install: true

jobs:
  fast_finish: true
  include:

    - name: Test
      stage: test
      script: ./scripts/run_travis.sh

    - name: Release
      stage: deploy
      before_script: docker login -u ehealthafricadevops -p $DOCKER_HUB_PASSWORD
      script: ./scripts/release.sh
      # release only if tag like #.#.# (never in forks or pull requests)
      if: |
        fork IS false AND \
        type != pull_request AND \
        tag =~ ^[0-9]+(\.[0-9]+){2}$
