version: "2.1"

networks:
  aether:
    external:
      name: aether_bootstrap_net

services:

  elasticsearch-consumer:
    extends:
      file: docker-compose-base.yml
      service: es-consumer-base
    environment:
      CONSUMER_PORT: 9009
      ES_CONSUMER_CONFIG_PATH: "/code/conf/consumer/consumer.json"
      ES_CONSUMER_KAFKA_CONFIG_PATH: "/code/conf/consumer/kafka.json"
      LOG_LEVEL: "DEBUG"
    networks:
      - aether
