version: "2.1"

services:

  # ES Test Containers

  consumer-test:
    extends:
      file: docker-compose-base.yml
      service: es-consumer-base
    volumes:
      - ./consumer/tests:/code/tests
    env_file:
     - test.env
    environment:
      TENANCY_HEADER: x-oauth-realm
      REDIS_DB: 0
      REDIS_HOST: localhost
      REDIS_PORT: 6379
      REDIS_PASSWORD: password
      
      CONSUMER_NAME: 'ES-TEST'
      
      KIBANA_URL: http://kibana:5601/kibana-app
      ELASTICSEARCH_URL: elasticsearch:9200
      ELASTICSEARCH_USER: admin
      ELASTICSEARCH_PASSWORD: admin
      
      SECURITY.PROTOCOL: SASL_SSL
      SASL.MECHANISM: PLAIN
      
      CONSUMER_PORT: 9099
      LOG_LEVEL: "DEBUG"
      ES_CONSUMER_CONFIG_PATH: "/code/tests/conf/consumer.json"
      ES_CONSUMER_KAFKA_CONFIG_PATH: "/code/tests/conf/kafka.json"
      CONNECT_RETRY_WAIT: 1
      STARTUP_CONNECTION_RETRY: 3


  elasticsearch-consumer-test-7:
    extends:
      service: consumer-test
    environment:
      ELASTICSEARCH_URL: "elasticsearch"
      INDEX_PATH: "/code/tests/test_index/es6"
      LOG_NAME: "ES_7-Consumer"
      KAFKA_TOPIC_TEMPLATE: "elastic7_{es_index_name}_{data_type}"

  elasticsearch-consumer-test-cloud:
    extends:
      service: consumer-test
    environment:
      INDEX_PATH: "/code/tests/test_index/es6"
      LOG_NAME: "ES_7-Consumer"
      KAFKA_URL: ${KAFKA_URL}
      SECURITY.PROTOCOL: SASL_SSL
      SASL.MECHANISM: PLAIN
      SASL.USERNAME: ${KAFKA_CONSUMER_USER}
      SASL.PASSWORD: ${KAFKA_CONSUMER_PASSWORD}
      KIBANA_URL: http://kibana:5601/kibana-app

      ELASTICSEARCH_URL: elasticsearch
      ELASTICSEARCH_PORT: 9200
      ELASTICSEARCH_USER: admin
      ELASTICSEARCH_PASSWORD: admin
    

  elasticsearch:
    image: amazon/opendistro-for-elasticsearch:${AMAZON_ES_VERSION:-1.2.0}
    environment:
      discovery.type: single-node
      opendistro_security.ssl.http.enabled: 'false'
    volumes:
      - ./conf/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties
      - ./conf/security.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/config.yml
    ports:
      - 9200:9200


  kibana:
    image: amazon/opendistro-for-elasticsearch-kibana:${AMAZON_ES_VERSION:-1.2.0}
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      ELASTICSEARCH_PRESERVEHOST: 'false'
      SERVER_BASEPATH: /kibana-app
      SERVER_REWRITEBASEPATH: 'true'
      opendistro_security.ssl.http.enabled: 'false'
    volumes:
      - ./conf/security.yml:/usr/share/kibana/plugins/opendistro_security/securityconfig/config.yml
      - ./conf/kibana.yml:/usr/share/kibana/config/kibana.yml
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
