version: "2.1"
services:

  es-consumer-base:
    build: consumer
    image: aether-elasticsearch-consumer
    stdin_open: true
    ports:
      - "9009:9009"
    volumes:
     - ./consumer:/code
    environment:
     - PYTHONUNBUFFERED=0
    command: start
