version: "2.4"

services:

  # ES Test Containers

  consumer-test:
    extends:
      file: docker-compose-base.yml
      service: es-consumer-base
    environment:
      TENANCY_HEADER: x-oauth-realm
      REDIS_DB: 0
      REDIS_HOST: localhost
      REDIS_PORT: 6379
      # REDIS_PASSWORD: password
      CONSUMER_NAME: 'ES-TEST'

      KIBANA_URL: http://kibana:5601/kibana-app
      ELASTICSEARCH_URL: elasticsearch:9200
      ELASTICSEARCH_USER: admin
      ELASTICSEARCH_PASSWORD: admin

      KAFKA_URL: kafka:29092
      INSECURE_KAFKA: "true"

      EXPOSE_PORT: 9013
      LOG_LEVEL: "ERROR"
      CONSUMER_CONFIG_PATH: "/code/tests/conf/consumer.json"
      CONSUMER_KAFKA_CONFIG_PATH: "/code/tests/conf/kafka.json"
      CONNECT_RETRY_WAIT: 1
      STARTUP_CONNECTION_RETRY: 3


  redis:
    image: redis:alpine


  # ---------------------------------
  # ES & Kibana
  # ---------------------------------

  elasticsearch:
    image: amazon/opendistro-for-elasticsearch:${AMAZON_ES_VERSION:-1.12.0}
    environment:
      discovery.type: single-node
      opendistro_security.ssl.http.enabled: 'false'
    volumes:
      - ./conf/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties
      - ./conf/security.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/config.yml
    ports:
      - 9200:9200

  kibana:
    image: amazon/opendistro-for-elasticsearch-kibana:${AMAZON_ES_VERSION:-1.12.0}
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      ELASTICSEARCH_PRESERVEHOST: 'false'
      SERVER_BASEPATH: /kibana-app
      SERVER_REWRITEBASEPATH: 'true'
      opendistro_security.ssl.http.enabled: 'false'
    volumes:
      - ./conf/security.yml:/usr/share/kibana/plugins/opendistro_security/securityconfig/config.yml
      - ./conf/kibana.yml:/usr/share/kibana/config/kibana.yml
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601


  # ---------------------------------
  # Kafka & Zookeeper
  # ---------------------------------

  zookeeper:
    image: confluentinc/cp-zookeeper:${CONFLUENTINC_VERSION:-latest}
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:${CONFLUENTINC_VERSION:-latest}
    links:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092
      ADVERTISED_HOST_NAME: kafka
