version: "2.4"
services:

  es-consumer-base:
    build: consumer
    image: aether-elasticsearch-consumer
    stdin_open: true
    volumes:
      - ./consumer:/code
    environment:
      - PYTHONUNBUFFERED=0
    command: start

  es-consumer-base-local:
    build:
      context: ./consumer
      dockerfile: Dockerfile.local
    image: aether-elasticsearch-consumer
    stdin_open: true
    volumes:
      - ./consumer:/code
    environment:
      - PYTHONUNBUFFERED=0
    command: start
