version: "2.1"
services:

  elasticsearch:
    extends:
      file: docker-compose-base.yml
      service: elasticsearch-base
    networks:
      - aether

  kibana:
    extends:
      file: docker-compose-base.yml
      service: kibana-base
    depends_on:
      - elasticsearch
    networks:
      - aether

  es-consumer:
    extends:
      file: docker-compose-base.yml
      service: es-consumer-base
    links:
      - elasticsearch
    networks:
      - aether

networks:
  aether:
    external:
      name: aether_internal
