version: "2.1"
services:
  elasticsearch-base-7:
    image: amazon/opendistro-for-elasticsearch:1.1.0
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"

  kibana-base:
    image: docker.elastic.co/kibana/kibana-oss:6.3.2
    ports:
      - "5601:5601"
    environment:
      kibana.index: "aether-demo-2"

  es-consumer-base:
    build: consumer
    image: aether-elasticsearch-consumer
    stdin_open: true
    ports:
      - "9009:9009"
    volumes:
     - ./consumer:/code
    environment:
     - PYTHONUNBUFFERED=0
    command: start
