version: "2.1"
services:

  # ES Test Containers

  consumer-test:
    extends:
      file: docker-compose-base.yml
      service: es-consumer-base
    networks:
      - test_net
    volumes:
      - ./consumer/tests:/code/tests
    environment:
      TENANCY_HEADER: x-tenant
      REDIS_DB: 0
      REDIS_HOST: localhost
      REDIS_PORT: 6379
      REDIS_PASSWORD: password
      CONSUMER_NAME: 'ES-TEST'
      ELASTICSEARCH_PORT: 9200
      KAFKA_URL: "kafka-test:29092"
      CONSUMER_PORT: 9099
      LOG_LEVEL: "DEBUG"
      ES_CONSUMER_CONFIG_PATH: "/code/tests/conf/consumer.json"
      ES_CONSUMER_KAFKA_CONFIG_PATH: "/code/tests/conf/kafka.json"
      CONNECT_RETRY_WAIT: 1
      STARTUP_CONNECTION_RETRY: 3


  elasticsearch-consumer-test-7:
    extends:
      service: consumer-test
    environment:
      ELASTICSEARCH_URL: "elasticsearch"
      INDEX_PATH: "/code/tests/test_index/es6"
      LOG_NAME: "ES_7-Consumer"
      KAFKA_TOPIC_TEMPLATE: "elastic7_{es_index_name}_{data_type}"

  elasticsearch-consumer-test-cloud:
    extends:
      service: consumer-test
    environment:
      INDEX_PATH: "/code/tests/test_index/es6"
      LOG_NAME: "ES_7-Consumer"
      KAFKA_URL: ${KAFKA_URL}
      SECURITY.PROTOCOL: ${KAFKA_SECURITY}
      SASL.MECHANISM: PLAIN
      SASL.USERNAME: ${KAFKA_CONSUMER_USER}
      SASL.PASSWORD: ${KAFKA_CONSUMER_PASSWORD}
      KIBANA_URL: http://kibana:5601/kibana-app

      ELASTICSEARCH_URL: elasticsearch
      ELASTICSEARCH_PORT: 9200
      ELASTICSEARCH_USER: admin
      ELASTICSEARCH_PASSWORD: admin
    networks:
      - test_net

  # ---------------------------------
  # Mock Data Container
  # ---------------------------------
  assets-test:
    build:
      context: ./aether-bootstrap/assets/generation
      dockerfile: Dockerfile
    volumes:
      - ./aether-bootstrap/assets:/code/assets
    environment:
      KERNEL_URL: http://kernel-test:9000
      KERNEL_USER: ${TEST_KERNEL_ADMIN_USERNAME}
      KERNEL_PASSWORD: ${TEST_KERNEL_ADMIN_PASSWORD}
      PROJECT_NAME: DefaultDemo
      SUBMISSION_ENDPOINT: default_mapping
    networks:
      - test_net

networks:
  test_net:
    external:
      name: aether_bootstrap_net
