version: "2.4"

networks:
  aether:
    external:
      name: aether_bootstrap_net

services:

  elasticsearch-consumer:
    extends:
      file: docker-compose-base.yml
      service: es-consumer-base
    environment:
      EXPOSE_PORT: 9009
      CONSUMER_CONFIG_PATH: "/code/conf/consumer/consumer.json"
      CONSUMER_KAFKA_CONFIG_PATH: "/code/conf/consumer/kafka.json"
      LOG_LEVEL: "DEBUG"
    networks:
      - aether
