version: "2.1"
services:

  elasticsearch-test:
    extends:
      file: docker-compose-base.yml
      service: elasticsearch-base
    networks:
      - test_net

  kibana-test:
    extends:
      file: docker-compose-base.yml
      service: kibana-base
    depends_on:
      - elasticsearch-test
    ports:
      - "5601:5601"
    environment:
      SERVER_HOST: 0.0.0.0
      ELASTICSEARCH_URL: http://elasticsearch-test
    networks:
      - test_net


  elasticsearch-consumer-test:
    extends:
      file: docker-compose-base.yml
      service: es-consumer-base
    networks:
      - test_net
    links:
      - elasticsearch-test
    volumes:
      - ./consumer/tests:/code/tests
    environment:
      ES_CONSUMER_CONFIG_PATH: "/code/tests/conf/consumer.json"
      ES_CONSUMER_KAFKA_CONFIG_PATH: "/code/tests/conf/kafka.json"

  # ---------------------------------
  # Mock Data Container
  # ---------------------------------

  assets-test:
    build:
      context: aether-bootstrap/assets/generation
      dockerfile: Dockerfile
    volumes:
      - ./aether-bootstrap/assets:/code/assets
    environment:
      KERNEL_URL: "http://kernel-test:9001"
      KERNEL_USER: "admin"
      KERNEL_PASSWORD: "adminadmin"
      PROJECT_NAME: "DefaultDemo"
      SUBMISSION_ENDPOINT: "default_mapping"
    networks:
      - test_net

networks:
  test_net:
    external:
      name: aether_test
